	--@diagnostic disable: undefined-global
	-- hyprland.lua
-- Generated by hypr-migrate from: hyprland.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       4 resolved
--   Config keys:     44 emitted
--   Monitors:        1
--   Keybinds:        52 total, 18 collapsed into loops
--   Window rules:    2 total, 1 merged
--   Workspace rules: 0
--   Exec commands:   5
--   Gestures:        1
--   Warnings:        12  ← search MIGRATION_WARNING
--   Review needed:   0  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

local terminal = "foot -e fish"
local fileManager = "EDITOR=nvim foot -e yazi"
local menu = "rofi -show drun"

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

hl.config({
    general = {
        allow_tearing = false,
        border_size = 2,
        ["col.active_border"] = {colors = { "rgba(ff4432ee)", "rgba(ffc700ee)" }, angle = 45},
        ["col.inactive_border"] = "rgba(595959aa)",
        gaps_in = 5,
        gaps_out = 20,
        layout = "dwindle",
        resize_on_border = false,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = true,
            passes = 1,
            size = 3,
            vibrancy = 0.1696,
        },
        inactive_opacity = 0.8,
        rounding = 10,
        rounding_power = 2,
        shadow = {
            color = "rgba(1a1a1aee)",
            enabled = true,
            range = 0,
            render_power = 3,
        },
    },
    input = {
        follow_mouse = 0,
        kb_layout = "us-de",
        kb_model = "",
        kb_options = "caps:escape,lv3:ralt_switch",
        kb_rules = "",
        kb_variant = "",
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
    misc = {
        disable_hyprland_logo = true,
        force_default_wallpaper = 0,
        vrr = 0,
    },
    cursor = {
        no_hardware_cursors = true,
    },
    dwindle = {
        preserve_split = true,
    },
    master = {
        new_status = "master",
    },
    animations = {
        enabled = true,
 		-- "yes, please :)",
    },
    autogenerated = 0,
})

hl.monitor({ output = "HDMI-A-1", mode = "1920x1080", position = "0x0" })

hl.window_rule({ match = { initial_title = "Picture in picture" }, float = true, opacity = "1.0 override", pin = true, size = {414, 234}, move = {1448, 113}})

hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("wl-color-picker clipboard"))
hl.bind(" + PRINT", hl.dsp.exec_cmd("flameshot gui"))
hl.bind("SUPER + V", hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
hl.bind("SUPER + RETURN", hl.dsp.exec_cmd(terminal))
hl.bind("SUPER + E", hl.dsp.exec_cmd(fileManager))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + SHIFT + Q", hl.dsp.window.kill())
hl.bind("SUPER + F", hl.dsp.window.fullscreen())
-- hl.bind("SUPER SHIFT + F", hl.dsp.window.float())
hl.bind("SUPER + SPACE", hl.dsp.exec_cmd(menu))
hl.bind("SUPER + P", hl.dsp.window.pin())
hl.bind("SUPER + O", hl.dsp.window.set_prop({prop = "opacity", value = "1.0"}))
hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }))
hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }))
hl.bind("SUPER + up", hl.dsp.focus({ direction = "u" }))
hl.bind("SUPER + down", hl.dsp.focus({ direction = "d" }))

-- PATTERN: 10 sequential binds collapsed to loop
for i = 1, 10 do
    hl.bind("SUPER + SHIFT + " .. (i % 10), hl.dsp.window.move({ workspace = tostring(i) }))
end

-- PATTERN: 10 sequential binds collapsed to loop
for i = 1, 10 do
    hl.bind("SUPER + " .. (i % 10), hl.dsp.focus({ workspace = tostring(i) }))
end

hl.bind(" + F7", hl.dsp.exec_cmd("sleep .05 && wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"))
hl.bind(" + F8", hl.dsp.exec_cmd("sleep .05 && wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 0"))
hl.bind(" + F8", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 1"), {release = true})
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind(" + KP_Left", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(" + KP_Begin", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind(" + KP_Right", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    --  hl.exec_cmd("wbg /home/blaze/Pownloads/wallpaper.png")
    hl.exec_cmd("relaunch-waybar")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("gnome-keyring-daemon --start --components=secret")
end)

hl.curve("default", {
    type = "bezier",
    points = { {0.25, 0.1}, {0.25, 1.0} }
})

hl.curve("easeOutQuint", {
    type = "bezier",
    points = { {0.23, 1.0}, {0.32, 1.0} }
})

hl.curve("easeInOutCubic", {
    type = "bezier",
    points = { {0.65, 0.05}, {0.36, 1.0} }
})

hl.curve("linear", {
    type = "bezier",
    points = { {0.0, 0.0}, {1.0, 1.0} }
})

hl.curve("almostLinear", {
    type = "bezier",
    points = { {0.5, 0.5}, {0.75, 1.0} }
})

hl.curve("quick", {
    type = "bezier",
    points = { {0.15, 0.0}, {0.1, 1.0} }
})

hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10.0,
    bezier = "default",
})

hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})

hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})

hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})

hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})

hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4.0,
    bezier = "easeOutQuint",
    style = "fade",
})

hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})

hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})

hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 7.0,
    bezier = "quick",
})
