font=NotoMono Nerd Font:size=12
font-bold=NotoMono Nerd Font:bold:size=12
font-italic=NotoMono Nerd Font:italic:size=12
dpi-aware=yes
resize-delay-ms=0
pad=2x2

# colors section
[colors]
foreground=FFFFFF
background=000000
regular0=000000
regular1=ff0000
regular2=00ff00
regular3=ffff00
regular4=0000ff
regular5=ff00ff
regular6=00ffff
regular7=c0c0c0

bright0=808080
bright1=ff0000
bright2=00ff00
bright3=ffff00
bright4=0000ff
bright5=ff00ff
bright6=00ffff
bright7=ffffff
# alpha=1.0

# cursor style
[cursor]
style=block
blink=no

# scrollback
[scrollback]
lines=10000
indicator-position=none
